# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/test_pmod_audio_design/test_pmod_audio_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pmod_audio_design || ORIG_REF_NAME==test_pmod_audio_design}]

# IP: bd/test_pmod_audio_design/ip/test_pmod_audio_design_clk_wiz_0_0/test_pmod_audio_design_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pmod_audio_design_clk_wiz_0_0 || ORIG_REF_NAME==test_pmod_audio_design_clk_wiz_0_0}]

# IP: bd/test_pmod_audio_design/ip/test_pmod_audio_design_pMOD_Audio_in_0_0/test_pmod_audio_design_pMOD_Audio_in_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pmod_audio_design_pMOD_Audio_in_0_0 || ORIG_REF_NAME==test_pmod_audio_design_pMOD_Audio_in_0_0}]

# IP: bd/test_pmod_audio_design/ip/test_pmod_audio_design_pMOD_Audio_out_0_0/test_pmod_audio_design_pMOD_Audio_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pmod_audio_design_pMOD_Audio_out_0_0 || ORIG_REF_NAME==test_pmod_audio_design_pMOD_Audio_out_0_0}]

# IP: bd/test_pmod_audio_design/ip/test_pmod_audio_design_upsizer_msb_0_1/test_pmod_audio_design_upsizer_msb_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pmod_audio_design_upsizer_msb_0_1 || ORIG_REF_NAME==test_pmod_audio_design_upsizer_msb_0_1}]

# IP: bd/test_pmod_audio_design/ip/test_pmod_audio_design_not_gate_0_0/test_pmod_audio_design_not_gate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pmod_audio_design_not_gate_0_0 || ORIG_REF_NAME==test_pmod_audio_design_not_gate_0_0}]

# XDC: bd/test_pmod_audio_design/ip/test_pmod_audio_design_clk_wiz_0_0/test_pmod_audio_design_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pmod_audio_design_clk_wiz_0_0 || ORIG_REF_NAME==test_pmod_audio_design_clk_wiz_0_0}] {/U0 }]/U0 ]]

# XDC: bd/test_pmod_audio_design/ip/test_pmod_audio_design_clk_wiz_0_0/test_pmod_audio_design_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pmod_audio_design_clk_wiz_0_0 || ORIG_REF_NAME==test_pmod_audio_design_clk_wiz_0_0}] {/U0 }]/U0 ]]

# XDC: bd/test_pmod_audio_design/ip/test_pmod_audio_design_clk_wiz_0_0/test_pmod_audio_design_clk_wiz_0_0_ooc.xdc

# XDC: bd/test_pmod_audio_design/test_pmod_audio_design_ooc.xdc
