# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param simulator.modelsimInstallPath F:/Altera/modelsim_ase/win32aloem
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000

create_project -in_memory -part xc7a200tfbg676-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/MASTER/LPSC/git/LPSC-FPDj_Soundmix/dev/fpga/Vivado_Frequency/Frequency_Analysis/Frequency_Analysis.cache/wt [current_project]
set_property parent.project_path D:/MASTER/LPSC/git/LPSC-FPDj_Soundmix/dev/fpga/Vivado_Frequency/Frequency_Analysis/Frequency_Analysis.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:ac701:part0:1.1 [current_project]
add_files -quiet D:/MASTER/LPSC/git/LPSC-FPDj_Soundmix/dev/fpga/Vivado_Frequency/Frequency_Analysis/Frequency_Analysis.runs/mult_gen_0_synth_1/mult_gen_0.dcp
set_property used_in_implementation false [get_files D:/MASTER/LPSC/git/LPSC-FPDj_Soundmix/dev/fpga/Vivado_Frequency/Frequency_Analysis/Frequency_Analysis.runs/mult_gen_0_synth_1/mult_gen_0.dcp]
add_files -quiet D:/MASTER/LPSC/git/LPSC-FPDj_Soundmix/dev/fpga/Vivado_Frequency/Frequency_Analysis/Frequency_Analysis.runs/xfft_0_synth_1/xfft_0.dcp
set_property used_in_implementation false [get_files D:/MASTER/LPSC/git/LPSC-FPDj_Soundmix/dev/fpga/Vivado_Frequency/Frequency_Analysis/Frequency_Analysis.runs/xfft_0_synth_1/xfft_0.dcp]
read_vhdl -library xil_defaultlib {
  D:/MASTER/LPSC/git/LPSC-FPDj_Soundmix/dev/fpga/src/FIR_Index_Package.vhd
  D:/MASTER/LPSC/git/LPSC-FPDj_Soundmix/dev/fpga/src/Package_FPDj.vhd
  D:/MASTER/LPSC/git/LPSC-FPDj_Soundmix/dev/fpga/src/Intensity_Bands_Extraction.vhd
  D:/MASTER/LPSC/git/LPSC-FPDj_Soundmix/dev/fpga/src/Frequency_Analysis_top.vhd
}
catch { write_hwdef -file Frequency_Analysis_top.hwdef }
synth_design -top Frequency_Analysis_top -part xc7a200tfbg676-2
write_checkpoint -noxdef Frequency_Analysis_top.dcp
catch { report_utilization -file Frequency_Analysis_top_utilization_synth.rpt -pb Frequency_Analysis_top_utilization_synth.pb }
